version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-v6.0
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=my_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always
    networks:
      red_interna:
        ipv4_address: 192.168.10.10
    ports:
      - 27017:27017
    volumes:
      - ./mongo-db-data/:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
    red_interna:
        ipam:
            config:
              - subnet: 192.168.10.0/24