version: '3.9'

services:
  micro_consume_ip:
    restart: always
    ports:
      - 8080:5000
    networks:
      default:
        ipv4_address: 192.168.10.50
    
    build: .
networks:
  default:
    name: mongo-v60_red_interna
    external: true